# Questão 1
SELECT P.NOME, P.SIGLA, P.TIPO, FA.NOME
FROM forca_armada FA, patente P, forca_patente FP
WHERE FA.ID_FORCA_ARMADA = FP.ID_FORCA_ARMADA
AND P.ID_PATENTE = FP.ID_PATENTE
AND FA.NOME = 'Exército'
AND P.TIPO = 'P';

# Questão 2
SELECT M.NOME , M.SOLDO
FROM MILITAR M, FORCA_PATENTE FP, FORCA_ARMADA FA
WHERE M.ID_FORCA_PATENTE = FP.ID_FORCA_PATENTE 
AND FP.ID_FORCA_ARMADA = FA.ID_FORCA_ARMADA 
AND FA.NOME = "MARINHA"
ORDER BY M.SOLDO DESC;

-- Mesmo Resultado porém sem necessidade de JOIN
SELECT NOME, SOLDO
FROM MILITAR
WHERE FORCA_EMIS_IDENT_MIL = 'MAR'
ORDER BY SOLDO DESC;

# Questão 3
SELECT M.NOME "MILITAR", P.NOME "PATENTE"
FROM MILITAR M, FORCA_PATENTE FP, FORCA_ARMADA FA, PATENTE P
WHERE M.ID_FORCA_PATENTE = FP.ID_FORCA_PATENTE 
AND FP.ID_FORCA_ARMADA = FA.ID_FORCA_ARMADA 
AND P.ID_PATENTE = FP.ID_PATENTE 
AND FA.NOME = "AERONAUTICA"
ORDER BY M.NOME;

# Questão 4
SELECT COUNT(FP.ID_FORCA_ARMADA) "QUANTIDADE PATENTES", FA.NOME "NOME"
FROM PATENTE P, FORCA_ARMADA FA, FORCA_PATENTE FP
WHERE P.ID_PATENTE = FP.ID_PATENTE 
AND FA.ID_FORCA_ARMADA = FP.ID_FORCA_ARMADA 
GROUP BY(FA.NOME);

# Questão 5
SELECT SUM(M.SOLDO), FA.ID_FORCA_ARMADA, FA.NOME
FROM MILITAR M, FORCA_ARMADA FA, FORCA_PATENTE FP, PATENTE P
WHERE M.ID_FORCA_PATENTE = FP.ID_FORCA_PATENTE 
AND FP.ID_FORCA_ARMADA = FA.ID_FORCA_ARMADA 
AND P.ID_PATENTE = FP.ID_PATENTE 
GROUP BY(FA.NOME);
