CREATE VIEW MIL
AS SELECT ID_MILITAR, NOME, SOLDO
FROM MILITAR
WHERE SOLDO <= 5000
WITH CHECK OPTION;

DROP VIEW MIL;

CREATE VIEW MIL
AS SELECT M.ID_MILITAR, M.NOME "NOME MILITAR", M.SOLDO, P.NOME "NOME PATENTE"
FROM MILITAR M, PATENTE P, FORCA_PATENTE FP, FORCA_ARMADA FA
WHERE 
	M.ID_FORCA_PATENTE = FP.ID_FORCA_PATENTE       AND
	P.ID_PATENTE       = FP.ID_PATENTE             AND
	FA.ID_FORCA_ARMADA = FP.ID_FORCA_ARMADA        AND
	FA.NOME = "Exército";
